### PR TITLE
Fixing Permission related issue. Fixes #11

### LINKED ISSUE #11: App crashes due to permission issue.
App crashes after clicking on Expenses tab.This is after the new update.
Tried a fresh install too.

Error Log from logcat:
```
 FATAL EXCEPTION: main
                                                   Process: com.ae.apps.tripmeter, PID: 11111
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ae.apps.tripmeter/com.ae.apps.tripmeter.activities.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{8d29387 11111:com.ae.apps.tripmeter/u0a182} (pid=11111, uid=10182) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                                    Caused by: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessRecord{8d29387 11111:com.ae.apps.tripmeter/u0a182} (pid=11111, uid=10182) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
                                                       at android.os.Parcel.readException(Parcel.java:1620)
                                                       at android.os.Parcel.readException(Parcel.java:1573)
                                                       at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3553)
                                                       at android.app.ActivityThread.acquireProvider(ActivityThread.java:4797)
                                                       at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2031)
                                                       at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1484)
                                                       at android.content.ContentResolver.query(ContentResolver.java:477)
                                                       at android.content.ContentResolver.query(ContentResolver.java:435)
                                                       at com.ae.apps.common.c.a.a(Unknown Source)
                                                       at com.ae.apps.common.c.a.<init>(Unknown Source)
                                                       at com.ae.apps.tripmeter.d.a.<init>(Unknown Source)
                                                       at com.ae.apps.tripmeter.d.b.<init>(Unknown Source)
                                                       at com.ae.apps.tripmeter.d.b.a(Unknown Source)
                                                       at com.ae.apps.tripmeter.b.h.a(Unknown Source)
                                                       at android.support.v4.b.l.j(Unknown Source)
                                                       at android.support.v4.b.r.a(Unknown Source)
                                                       at android.support.v4.b.r.z(Unknown Source)
                                                       at android.support.v4.b.r.a(Unknown Source)
                                                       at android.support.v4.b.r.b(Unknown Source)
                                                       at android.support.v4.b.r.f(Unknown Source)
                                                       at android.support.v4.b.o.n(Unknown Source)
                                                       at android.support.v4.b.m.onStart(Unknown Source)
                                                       at android.support.v7.app.c.onStart(Unknown Source)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
                                                       at android.app.Activity.performStart(Activity.java:6320)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2386)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5441) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

### PR DESCRIPTION
**Pull request by RaghuChandrasekaran**
Support for Android M & above.
**EDIT:Update of tasks**
**Summary of Changes Requested:**

- [x] Rename String values to str_permission_contacts_reason and such to allow multiple values.

- [x] On entering to the expenses fragment if permission is already granted paint the normal view.If permission is to be requested paint a empty view.

- [x] onRequestPermissionsResult()
PERMISSION_GRANTED -> inflate(R.layout.fragment_trips_list, container, false); and add to view// we could cache the inflator
PERMISSION_DENIED -> view.add(new TextView()); // add to empty view already created

Two important tasks remain before merging related to transition of fragments for user. 

In onRequestPermissionsResult we need to handle both probable cases (allow & deny).

Now the app won't crash but on denying/allowing it would remain in the same fragment and there would be no possible action for user to do as the view was rendered without FloatingActionButton being binded to action.

Expected: On allow we need to re-render fragment and on denial move to Price tab.
I will need help on implementing this as the options I tried did not work perfectly.

Updated Screenshots: Android N

screenshot_1488898778
screenshot_1488899091
screenshot_1488899083

### CODE REVIEW

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java [hunk 1]
```diff
@@ -85,6 +95,47 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
         // Removing default profile feature
         // checkForDefaultProfile();
 
+        view=createViewHandlingPermissions(view,list);
```
Comment (midhunhk) [inline app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: avoid assignments to variables that are passed in as parameters. Sonar violation

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java [hunk 2]
```diff
@@ -85,6 +95,47 @@ public View onCreateView(LayoutInflater inflater, ViewGroup container,
...
+
+        return view;
+    }
+
+    private View createViewHandlingPermissions(View view,View list){
```
Comment (midhunhk) [inline app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: we can split this method into 2.
a) test for permission
b) return view

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java [hunk 3]
```diff
@@ -103,10 +154,30 @@ public void onClick(View v) {
...
+    @Override
+    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
+        switch (requestCode) {
+            case PERMISSIONS_REQUEST_READ_CONTACTS: {
+                if (grantResults.length > 0
+                        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+                    //TODO: Reload this Fragment.Otherwise the FAB won't work
+                } else {
+                    Toast.makeText(getActivity(), "This feature needs access to contacts.", Toast.LENGTH_LONG).show();
+                    //TODO: Direct user to price fragment as this fragment cannot be used
```
Comment (midhunhk) [inline app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: lets create a new TextView saying "Need permission for accessing contacts for this feature to work" and remain in the same fragment. Instead of navigating to another fragment.

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java [hunk 4]
```diff
@@ -103,10 +154,30 @@ public void onClick(View v) {
...
     }
 
+
+    @Override
+    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
+        switch (requestCode) {
+            case PERMISSIONS_REQUEST_READ_CONTACTS: {
+                if (grantResults.length > 0
+                        && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
+                    //TODO: Reload this Fragment.Otherwise the FAB won't work
```
Comment (midhunhk) [inline app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: Is this issue caused by onRequestPermissionsResult being Async. Could we just have the code to paint the fragment called here before requestPermissions was implemented?

onCreateView() -> return an empty view
onRequestPermissionsResult()
    PERMISSION_GRANTED -> inflate(R.layout.fragment_trips_list, container, false); and add to view// we could cache the inflator
    PERMISSION_DENIED -> view.add(new TextView()); // add to empty view already created

File: app/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -134,6 +134,9 @@
 
     <string name="pref_title_vibrate">Vibrate</string>
 
+    <string name="str_perm_title">Permission Needed</string>
+    <string name="str_perm_reason">Contacts access is needed for this feature</string>
```
Comment (midhunhk) [inline app/src/main/res/values/strings.xml]: we could have this named for "contacts permission". we would be following similar steps for internet.

e.g; str_permission_contacts_reason

**Review by midhunhk — CHANGES_REQUESTED** [review]
have added some review comments which can complete this change, although the current code fixes the issue.

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java (hunk 4 above)
Comment (RaghuChandrasekaran) [reply app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: The actual issue is caused due to reading of contacts during instantiation of contacts manager which attempts to fetch all contacts.
[Relevant Lines](https://github.com/midhunhk/ae-apps-library/blob/master/app/src/main/java/com/ae/apps/common/managers/ContactManager.java#L72-L76)

A ideal fix will be refactoring the lib to be clean i.e when creating a new object refrain from doing other tasks and expose public methods to perform fetching and other similar tasks.

**Comment by RaghuChandrasekaran** [comment]
Summary of Changes Requested:

- [ ] Rename String values to str_permission_contacts_reason and such to allow multiple values.

- [ ] On entering to the expenses fragment if permission is already granted paint the normal view.If permission is to be requested paint a empty view.

- [ ] onRequestPermissionsResult()
PERMISSION_GRANTED -> inflate(R.layout.fragment_trips_list, container, false); and add to view// we could cache the inflator
PERMISSION_DENIED -> view.add(new TextView()); // add to empty view already created

**Comment by RaghuChandrasekaran** [comment]
` onRequestPermissionsResult() `can be handled in MainActivity or in the fragment itself.It depends on how we request permission.If we use 

```
        ActivityCompat.requestPermissions(thisActivity,
                new String[]{Manifest.permission.READ_CONTACTS},
                MY_PERMISSIONS_REQUEST_READ_CONTACTS);
```
the callback in  Activity is called and if we use,
`requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},                       PERMISSIONS_REQUEST_READ_CONTACTS);`

the callback in fragment is called.
Since we might ask for more permissions in future what will be a better way of handling this task?
If we are going to handle this from MainActivity then the above idea of painting empty view can be handled in some other alternative way?

**Comment by midhunhk** [comment]
Since the requestPermissions() is ASYNC, we can have this checked in separate Fragment itself. Handling ASYNC code to load a Fragment is more work.

Furthermore MainActivity checking for permissions on behalf of a child Fragment is more work on MainActivity's end. Conceptually MainActivity is a Controller and each Fragment would be a self contained View.

It should ideally load child Fragments and let them decide on

- Check if permissions needed for that feature
- Decide what to do if permissions are not granted
- Paint the view

File: app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java (hunk 4 above)
Comment (RaghuChandrasekaran) [reply app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: > A ideal fix will be refactoring the lib to be clean i.e when creating a new object refrain from doing other tasks and expose public methods to perform fetching and other similar tasks.

@midhunhk  Any thoughts on that?

Comment (midhunhk) [reply app/src/main/java/com/ae/apps/tripmeter/fragments/TripsListFragment.java]: That's a good idea. :+1:  I also want to add a `fetchAllContactsAsync()` method to load the data in a background thread.

One problem with this change is a few other apps consuming this library, so this would be an API breaking change. Will take this up post Balanjar release when I need to continue with MessageCounter's Uniforn release :unicorn: 

https://github.com/midhunhk/ae-apps-library#implementation

Opened an issue in lib project:
https://github.com/midhunhk/ae-apps-library/issues/2

**Comment by RaghuChandrasekaran** [comment]
Updated code to match the requested changes and also Screenshots.

**Review by midhunhk — APPROVED** [review]
The changes look good :+1: , will merge to midhunhk:balanjar and test the changes
